server:
  port: 19000
  servlet:
    contextPath: /jwt-rsa

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.200.159:18020/davebase?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
#    url: jdbc:log4jdbc:mariadb://192.168.45.67:18020/davebase?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: base
    password: "0000"
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

jwt:
  secret: ImPossible$$
  token-validity-ms: 3600000

apikey:
  secret: ImPossible$$$$$$ImPossible$$$$$$
  iv: ImPossible$$$$$$
  delimiter: $$$

directory:
  user:
    image: /home/dave/server-aa/api/data/user/image

logging:
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:%line] - %msg%n"
    rolling-file-name: "/home/dave/server-aa/api/log/loginRSA-develop.%d{yyyy-MM-dd}.%i.log"
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:%line] - %msg%n"
  file:
    name: /home/dave/server-aa/api/log/loginRSA-develop.log
    max-history: 30
  level:
    org:
      springframework: INFO
    com:
      example:
        loginJwtRSA: TRACE
    log4jdbc:
      log4j2: ERROR
#    jdbc:
#      sqlonly: TRACE
#      sqltiming: TRACE
#      resultsettable: TRACE
#      audit: TRACE
#      resultset: TRACE
#      connection: TRACE
