server:
  port: 8081
  servlet:
    contextPath: /app-base

spring:
  datasource:
#    url: jdbc:log4jdbc:mariadb://192.168.200.159:3306/davebase?characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:log4jdbc:mariadb://192.168.45.67:3306/davebase?characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: base
    password: "0000"

jwt:
  secret: ImPossible$$
  token-validity-ms: 3600000

apikey:
  secret: ImPossible$$$$$$ImPossible$$$$$$
  iv: ImPossible$$$$$$
  delimiter: $$$

directory:
  user:
    image: /home/dave/loginRSA/data/user/image

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:%line] - %msg%n"
    rolling-file-name: "/home/dave/loginRSA/log/loginRSA-develop.%d{yyyy-MM-dd}.%i.log"
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:%line] - %msg%n"
  file:
    name: /home/dave/loginRSA/log/loginRSA-develop.log
    max-history: 30
  level:
    org:
      springframework: INFO
    com:
      example:
        loginJwtRSA: TRACE
    log4jdbc:
      log4j2: ERROR
#    jdbc:
#      sqlonly: TRACE
#      sqltiming: TRACE
#      resultsettable: TRACE
#      audit: TRACE
#      resultset: TRACE
#      connection: TRACE
