# @BaseURL = http://localhost:28888/local
@BaseURL = http://localhost:29999/test

### TEST login success if password is "18"
POST {{BaseURL}}/api/v1/security/signin HTTP/1.1
content-Type: application/json

{
    "password": "18"
}
