# @BaseURL = http://localhost:8080
@BaseURL = http://localhost:28888/local/api/v1
# @BaseURL = http://localhost:29999/test/api/v1

### signup
POST {{BaseURL}}/auth/signup HTTP/1.1
content-Type: application/json

{
    "username": "eeee",
    "password": "0000"
}

### signin
POST {{BaseURL}}/auth/signin HTTP/1.1
content-Type: application/json

{
    "username": "aaaa",
    "password": "0000"
}

### TEST
POST {{BaseURL}}/user/getAll HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiJdLCJpYXQiOjE2Nzc3NzA4MDAsImV4cCI6MTY3Nzc3NDQwMH0.snMyzNm_mivu6Y02wTUkWFRzXdczzP4vTR7t133TosQ

{

}
